include = [
    "cars.toml",
    "trains.toml",
    "bus.toml",
    "tram.toml",
    "metro.toml",
    "bike.toml",
    "scooter.toml"
]
[[vehicle]]
name = "car"
co2 = 0.166
[[vehicle]]
name = "train"
kwh = 0.0000125
[[vehicle]]
name = "bus"
co2 = 0.93
[[vehicle]]
name = "tram"
kwh = 0.0000125
[[vehicle]]
name = "metro"
kwh = 0.0000116

[[vehicle]]
name = "bike"
co2 = 0.014
[[vehicle]]
name = "scooter"
co2 = 0.009

