[[depot]]
vehicles = [
    {"name" = "e-bus", "share" = 0.2},
    {"name" = "ice-bus", "share" = 0.8},
]
lines = [
    "169",
    "369"
]

[[depot]]
vehicles = [
    {"name" = "e-bus", "share" = 0.8},
    {"name" = "ice-bus", "share" = 0.2},
]
lines = [
    "269",
    "X69",
    "165",
    "164"
]

[[depot]]
vehicles = [
    {"name" = "e-bus", "share" = 0.5},
    {"name" = "ice-bus", "share" = 0.5},
]
lines = [
    "363",
    "161",
]
