server:
  port: 8080

client:
  timeout: 200

distance-service:
  address: http://localhost:8082
  uri: /v1/calc/distance

co2-service:
  address: http://localhost:8083
  uri: /v1/calc/co2

gamification-service:
  address: http://localhost:8084
  uri: /v1/calc/points
          
