server:
  port: 8080
  connection-timeout: 1s

client:
  timeout: 200

distance-service:
  address: http://localhost:8084
  uri: /v1/calc/distance

co2-service:
  address: http://localhost:8083
  uri: /v1/calc/co2

          
