apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ lower (include "ecotrekker.name" .) }}-vehicle-depot-deployment
  labels:
    {{- include "ecotrekker.labels" . | nindent 4 }}
    app.kubernetes.io/microservice: vehicle-depot
spec:
  replicas: {{ .Values.ecotrekker.vehicledepot.replicas }}
  selector:
    matchLabels:
      {{- include "ecotrekker.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/microservice: vehicle-depot
  template:
    metadata:
      labels:
        {{- include "ecotrekker.labels" . | nindent 8 }}
        app.kubernetes.io/microservice: vehicle-depot
    spec:
      containers:
      - name: {{ lower (include "ecotrekker.name" .) }}-vehicle-depot
        image: {{ .Values.ecotrekker.vehicledepot.image }}
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /status/alive
            port: 8080
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /status/ready
            port: 8080
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: {{ lower (include "ecotrekker.name" .) }}-vehicle-depot-service
  labels:
    {{- include "ecotrekker.labels" . | nindent 4 }}
    app.kubernetes.io/microservice: vehicle-depot
spec:
  selector:
    {{- include "ecotrekker.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/microservice: vehicle-depot
  ports:
    - name: rest
      protocol: TCP
      port: 8080
      targetPort: 8080
