apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ lower (include "ecotrekker.name" .) }}-rest-api-deployment
  labels:
    {{- include "ecotrekker.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.ecotrekker.restapi.replicas }}
  selector:
    matchLabels:
      {{- include "ecotrekker.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ecotrekker.labels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ lower (include "ecotrekker.name" .) }}-rest-api
        image: {{ .Values.ecotrekker.restapi.image }}
        ports:
        - containerPort: 8080
        env:
        {{ if .Values.kafka.namespace }}
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: {{ lower (include "ecotrekker.name" .) }}-kafka-cluster-kafka-bootstrap.{{ .Values.kafka.namespace }}:9092
        {{ else }}
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: {{ lower (include "ecotrekker.name" .) }}-kafka-cluster-kafka-bootstrap:9092
        {{ end }}
