apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ lower (include "ecotrekker.name" .) }}-grid-co2-cache-deployment
  labels:
    {{- include "ecotrekker.labels" . | nindent 4 }}
    app.kubernetes.io/microservice: grid-co2-cache
spec:
  replicas: {{ .Values.ecotrekker.gridco2cache.replicas }}
  selector:
    matchLabels:
      {{- include "ecotrekker.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/microservice: grid-co2-cache
  template:
    metadata:
      labels:
        {{- include "ecotrekker.labels" . | nindent 8 }}
        app.kubernetes.io/microservice: grid-co2-cache
    spec:
      containers:
      - name: {{ lower (include "ecotrekker.name" .) }}-grid-co2-cache
        image: {{ .Values.ecotrekker.gridco2cache.image }}
        resources:
          requests:
            cpu: "64m"
            memory: "256Mi"
          limits:
            cpu: "128m"
            memory: "384Mi"
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /status/alive
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /status/ready
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: {{ lower (include "ecotrekker.name" .) }}-grid-co2-cache-service
  labels:
    {{- include "ecotrekker.labels" . | nindent 4 }}
    app.kubernetes.io/microservice: grid-co2-cache
spec:
  selector:
    {{- include "ecotrekker.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/microservice: grid-co2-cache
  ports:
    - name: rest
      protocol: TCP
      port: 8080
      targetPort: 8080
