apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ lower (include "ecotrekker.name" .) }}-vehicle-consumption-deployment
  labels:
    {{- include "ecotrekker.labels" . | nindent 4 }}
    app.kubernetes.io/microservice: vehicle-consumption
spec:
  replicas: {{ .Values.ecotrekker.co2calculator.replicas }}
  selector:
    matchLabels:
      {{- include "ecotrekker.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/microservice: vehicle-consumption
  template:
    metadata:
      labels:
        {{- include "ecotrekker.labels" . | nindent 8 }}
        app.kubernetes.io/microservice: vehicle-consumption
    spec:
      containers:
      - name: {{ lower (include "ecotrekker.name" .) }}-vehicle-consumption
        image: {{ .Values.ecotrekker.vehicleconsumption.image }}
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /status/alive
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /status/ready
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: {{ lower (include "ecotrekker.name" .) }}-vehicle-consumption-service
  labels:
    {{- include "ecotrekker.labels" . | nindent 4 }}
    app.kubernetes.io/microservice: vehicle-consumption
spec:
  selector:
    {{- include "ecotrekker.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/microservice: vehicle-consumption
  ports:
    - name: rest
      protocol: TCP
      port: 8080
      targetPort: 8080
