apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ lower (include "ecotrekker.name" .) }}-vehicle-consumption-deployment
  labels:
    {{- include "ecotrekker.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.ecotrekker.co2calculator.replicas }}
  selector:
    matchLabels:
      {{- include "ecotrekker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ecotrekker.labels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ lower (include "ecotrekker.name" .) }}-vehicle-consumption
        image: {{ .Values.ecotrekker.vehicleconsumption.image }}
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ lower (include "ecotrekker.name" .) }}-vehicle-consumption-deployment
  labels:
    {{- include "ecotrekker.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "ecotrekker.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8080
