/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ecotrekker.publictransportdistance;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class PubTransportApp {
    public static void main(String[] args) {
        SpringApplication.run(PubTransportApp.class, args);
    }
}
