/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ecotrekker.gridco2cache;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        assertTrue(true);
    }
}
