include = [
    "cars.toml",
    "trains.toml",
    "bus.toml",
    "tram.toml",
    "metro.toml",
    "bike.toml",
    "scooter.toml"
]
[[vehicle]]
name = "car"
co2 = 0.162
[[vehicle]]
name = "train"
kwh = 0.0000724
#co2 = 0.072
[[vehicle]]
name = "bus"
co2 = 0.108
[[vehicle]]
name = "tram"
kwh = 0.00002
# co2 = 0.072
[[vehicle]]
name = "metro"
kwh = 0.000044
#co2 = 0.080

[[vehicle]]
name = "bike"
co2 = 0.022
[[vehicle]]
name = "scooter"
co2 = 0.080

